### ISSUE TITLE
[Feature][React native] [Android] [Face blur]: Need option props to hide or show square focus in camera screen and also ability to change the color of square focus.

### ISSUE THREAD

**Issue by karventhan13** [depakn/rn-camera-faceblur#2]
Android vivo y21
android12

refer screenshot
![Screenshot_20240816_172631](https://github.com/user-attachments/assets/9eba70f0-09b4-4f4f-9391-f2ceff900920)

**Comment by depakn** [comment]
The bounding box is remove, since its not needed.
